// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Chat/Chat.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Chat {

  /// <summary>Holder for reflection information generated from Chat/Chat.proto</summary>
  public static partial class ChatReflection {

    #region Descriptor
    /// <summary>File descriptor for Chat/Chat.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ChatReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9DaGF0L0NoYXQucHJvdG8aH2dvb2dsZS9wcm90b2J1Zi90aW1lc3RhbXAu",
            "cHJvdG8aD0NoYXQvVXNlci5wcm90byJuCg1TU2VuZENoYXRUZXh0Eh4KC3Nl",
            "bmRlcl9pbmZvGAEgASgLMgkuVXNlckluZm8SFwoEY2hhdBgCIAEoCzIJLkNo",
            "YXRUZXh0EhMKC3Jvb21fbnVtYmVyGAMgASgEEg8KB2NoYXRfaWQYBCABKAUi",
            "bgoNU1NlbmRDaGF0SWNvbhIeCgtzZW5kZXJfaW5mbxgBIAEoCzIJLlVzZXJJ",
            "bmZvEhcKBGNoYXQYAiABKAsyCS5DaGF0SWNvbhITCgtyb29tX251bWJlchgD",
            "IAEoBBIPCgdjaGF0X2lkGAQgASgFIlAKCUNTZW5kQ2hhdBIdCgVlcnJvchgB",
            "IAEoDjIOLlNlbmRDaGF0RXJyb3ISEwoLcm9vbV9udW1iZXIYAiABKAQSDwoH",
            "Y2hhdF9pZBgDIAEoBSJZCglDQ2hhdFRleHQSHgoLc2VuZGVyX2luZm8YASAB",
            "KAsyCS5Vc2VySW5mbxIXCgRjaGF0GAIgASgLMgkuQ2hhdFRleHQSEwoLcm9v",
            "bV9udW1iZXIYAyABKAQiWQoJQ0NoYXRJY29uEh4KC3NlbmRlcl9pbmZvGAEg",
            "ASgLMgkuVXNlckluZm8SFwoEY2hhdBgCIAEoCzIJLkNoYXRJY29uEhMKC3Jv",
            "b21fbnVtYmVyGAMgASgEImsKCENoYXRCYXNlEhIKCmNoYXRfZGJfaWQYASAB",
            "KAQSHAoJY2hhdF90eXBlGAIgASgOMgkuQ2hhdFR5cGUSLQoJdGltZXN0YW1w",
            "GAMgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcCI1CghDaGF0VGV4",
            "dBIcCgljaGF0X2Jhc2UYASABKAsyCS5DaGF0QmFzZRILCgNtc2cYAiABKAki",
            "OQoIQ2hhdEljb24SHAoJY2hhdF9iYXNlGAEgASgLMgkuQ2hhdEJhc2USDwoH",
            "aWNvbl9pZBgCIAEoDSpJCghDaGF0VHlwZRIVChFDSEFUX1RZUEVfSU5WQUxJ",
            "RBAAEhIKDkNIQVRfVFlQRV9URVhUEAESEgoOQ0hBVF9UWVBFX0lDT04QAiqo",
            "AQoNU2VuZENoYXRFcnJvchIbChdTRU5EX0NIQVRfRVJST1JfSU5WQUxJRBAA",
            "EhsKF1NFTkRfQ0hBVF9FUlJPUl9TVUNDRVNTEAESIAocU0VORF9DSEFUX0VS",
            "Uk9SX05PX1NVQ0hfUk9PTRACEiAKHFNFTkRfQ0hBVF9FUlJPUl9ST09NX1JF",
            "TU9WRUQQAxIZChVTRU5EX0NIQVRfRVJST1JfT1RIRVIQBEIHqgIEQ2hhdGIG",
            "cHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, global::Chat.UserReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Chat.ChatType), typeof(global::Chat.SendChatError), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Chat.SSendChatText), global::Chat.SSendChatText.Parser, new[]{ "SenderInfo", "Chat", "RoomNumber", "ChatId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Chat.SSendChatIcon), global::Chat.SSendChatIcon.Parser, new[]{ "SenderInfo", "Chat", "RoomNumber", "ChatId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Chat.CSendChat), global::Chat.CSendChat.Parser, new[]{ "Error", "RoomNumber", "ChatId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Chat.CChatText), global::Chat.CChatText.Parser, new[]{ "SenderInfo", "Chat", "RoomNumber" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Chat.CChatIcon), global::Chat.CChatIcon.Parser, new[]{ "SenderInfo", "Chat", "RoomNumber" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Chat.ChatBase), global::Chat.ChatBase.Parser, new[]{ "ChatDbId", "ChatType", "Timestamp" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Chat.ChatText), global::Chat.ChatText.Parser, new[]{ "ChatBase", "Msg" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Chat.ChatIcon), global::Chat.ChatIcon.Parser, new[]{ "ChatBase", "IconId" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum ChatType {
    [pbr::OriginalName("CHAT_TYPE_INVALID")] Invalid = 0,
    [pbr::OriginalName("CHAT_TYPE_TEXT")] Text = 1,
    [pbr::OriginalName("CHAT_TYPE_ICON")] Icon = 2,
  }

  public enum SendChatError {
    [pbr::OriginalName("SEND_CHAT_ERROR_INVALID")] Invalid = 0,
    [pbr::OriginalName("SEND_CHAT_ERROR_SUCCESS")] Success = 1,
    [pbr::OriginalName("SEND_CHAT_ERROR_NO_SUCH_ROOM")] NoSuchRoom = 2,
    [pbr::OriginalName("SEND_CHAT_ERROR_ROOM_REMOVED")] RoomRemoved = 3,
    [pbr::OriginalName("SEND_CHAT_ERROR_OTHER")] Other = 4,
  }

  #endregion

  #region Messages
  public sealed partial class SSendChatText : pb::IMessage<SSendChatText>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SSendChatText> _parser = new pb::MessageParser<SSendChatText>(() => new SSendChatText());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SSendChatText> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Chat.ChatReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SSendChatText() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SSendChatText(SSendChatText other) : this() {
      senderInfo_ = other.senderInfo_ != null ? other.senderInfo_.Clone() : null;
      chat_ = other.chat_ != null ? other.chat_.Clone() : null;
      roomNumber_ = other.roomNumber_;
      chatId_ = other.chatId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SSendChatText Clone() {
      return new SSendChatText(this);
    }

    /// <summary>Field number for the "sender_info" field.</summary>
    public const int SenderInfoFieldNumber = 1;
    private global::Chat.UserInfo senderInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Chat.UserInfo SenderInfo {
      get { return senderInfo_; }
      set {
        senderInfo_ = value;
      }
    }

    /// <summary>Field number for the "chat" field.</summary>
    public const int ChatFieldNumber = 2;
    private global::Chat.ChatText chat_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Chat.ChatText Chat {
      get { return chat_; }
      set {
        chat_ = value;
      }
    }

    /// <summary>Field number for the "room_number" field.</summary>
    public const int RoomNumberFieldNumber = 3;
    private ulong roomNumber_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong RoomNumber {
      get { return roomNumber_; }
      set {
        roomNumber_ = value;
      }
    }

    /// <summary>Field number for the "chat_id" field.</summary>
    public const int ChatIdFieldNumber = 4;
    private int chatId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ChatId {
      get { return chatId_; }
      set {
        chatId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SSendChatText);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SSendChatText other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(SenderInfo, other.SenderInfo)) return false;
      if (!object.Equals(Chat, other.Chat)) return false;
      if (RoomNumber != other.RoomNumber) return false;
      if (ChatId != other.ChatId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (senderInfo_ != null) hash ^= SenderInfo.GetHashCode();
      if (chat_ != null) hash ^= Chat.GetHashCode();
      if (RoomNumber != 0UL) hash ^= RoomNumber.GetHashCode();
      if (ChatId != 0) hash ^= ChatId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (senderInfo_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(SenderInfo);
      }
      if (chat_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Chat);
      }
      if (RoomNumber != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(RoomNumber);
      }
      if (ChatId != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(ChatId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (senderInfo_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(SenderInfo);
      }
      if (chat_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Chat);
      }
      if (RoomNumber != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(RoomNumber);
      }
      if (ChatId != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(ChatId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (senderInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SenderInfo);
      }
      if (chat_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Chat);
      }
      if (RoomNumber != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(RoomNumber);
      }
      if (ChatId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ChatId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SSendChatText other) {
      if (other == null) {
        return;
      }
      if (other.senderInfo_ != null) {
        if (senderInfo_ == null) {
          SenderInfo = new global::Chat.UserInfo();
        }
        SenderInfo.MergeFrom(other.SenderInfo);
      }
      if (other.chat_ != null) {
        if (chat_ == null) {
          Chat = new global::Chat.ChatText();
        }
        Chat.MergeFrom(other.Chat);
      }
      if (other.RoomNumber != 0UL) {
        RoomNumber = other.RoomNumber;
      }
      if (other.ChatId != 0) {
        ChatId = other.ChatId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (senderInfo_ == null) {
              SenderInfo = new global::Chat.UserInfo();
            }
            input.ReadMessage(SenderInfo);
            break;
          }
          case 18: {
            if (chat_ == null) {
              Chat = new global::Chat.ChatText();
            }
            input.ReadMessage(Chat);
            break;
          }
          case 24: {
            RoomNumber = input.ReadUInt64();
            break;
          }
          case 32: {
            ChatId = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (senderInfo_ == null) {
              SenderInfo = new global::Chat.UserInfo();
            }
            input.ReadMessage(SenderInfo);
            break;
          }
          case 18: {
            if (chat_ == null) {
              Chat = new global::Chat.ChatText();
            }
            input.ReadMessage(Chat);
            break;
          }
          case 24: {
            RoomNumber = input.ReadUInt64();
            break;
          }
          case 32: {
            ChatId = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class SSendChatIcon : pb::IMessage<SSendChatIcon>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SSendChatIcon> _parser = new pb::MessageParser<SSendChatIcon>(() => new SSendChatIcon());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SSendChatIcon> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Chat.ChatReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SSendChatIcon() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SSendChatIcon(SSendChatIcon other) : this() {
      senderInfo_ = other.senderInfo_ != null ? other.senderInfo_.Clone() : null;
      chat_ = other.chat_ != null ? other.chat_.Clone() : null;
      roomNumber_ = other.roomNumber_;
      chatId_ = other.chatId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SSendChatIcon Clone() {
      return new SSendChatIcon(this);
    }

    /// <summary>Field number for the "sender_info" field.</summary>
    public const int SenderInfoFieldNumber = 1;
    private global::Chat.UserInfo senderInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Chat.UserInfo SenderInfo {
      get { return senderInfo_; }
      set {
        senderInfo_ = value;
      }
    }

    /// <summary>Field number for the "chat" field.</summary>
    public const int ChatFieldNumber = 2;
    private global::Chat.ChatIcon chat_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Chat.ChatIcon Chat {
      get { return chat_; }
      set {
        chat_ = value;
      }
    }

    /// <summary>Field number for the "room_number" field.</summary>
    public const int RoomNumberFieldNumber = 3;
    private ulong roomNumber_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong RoomNumber {
      get { return roomNumber_; }
      set {
        roomNumber_ = value;
      }
    }

    /// <summary>Field number for the "chat_id" field.</summary>
    public const int ChatIdFieldNumber = 4;
    private int chatId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ChatId {
      get { return chatId_; }
      set {
        chatId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SSendChatIcon);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SSendChatIcon other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(SenderInfo, other.SenderInfo)) return false;
      if (!object.Equals(Chat, other.Chat)) return false;
      if (RoomNumber != other.RoomNumber) return false;
      if (ChatId != other.ChatId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (senderInfo_ != null) hash ^= SenderInfo.GetHashCode();
      if (chat_ != null) hash ^= Chat.GetHashCode();
      if (RoomNumber != 0UL) hash ^= RoomNumber.GetHashCode();
      if (ChatId != 0) hash ^= ChatId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (senderInfo_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(SenderInfo);
      }
      if (chat_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Chat);
      }
      if (RoomNumber != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(RoomNumber);
      }
      if (ChatId != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(ChatId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (senderInfo_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(SenderInfo);
      }
      if (chat_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Chat);
      }
      if (RoomNumber != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(RoomNumber);
      }
      if (ChatId != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(ChatId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (senderInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SenderInfo);
      }
      if (chat_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Chat);
      }
      if (RoomNumber != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(RoomNumber);
      }
      if (ChatId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ChatId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SSendChatIcon other) {
      if (other == null) {
        return;
      }
      if (other.senderInfo_ != null) {
        if (senderInfo_ == null) {
          SenderInfo = new global::Chat.UserInfo();
        }
        SenderInfo.MergeFrom(other.SenderInfo);
      }
      if (other.chat_ != null) {
        if (chat_ == null) {
          Chat = new global::Chat.ChatIcon();
        }
        Chat.MergeFrom(other.Chat);
      }
      if (other.RoomNumber != 0UL) {
        RoomNumber = other.RoomNumber;
      }
      if (other.ChatId != 0) {
        ChatId = other.ChatId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (senderInfo_ == null) {
              SenderInfo = new global::Chat.UserInfo();
            }
            input.ReadMessage(SenderInfo);
            break;
          }
          case 18: {
            if (chat_ == null) {
              Chat = new global::Chat.ChatIcon();
            }
            input.ReadMessage(Chat);
            break;
          }
          case 24: {
            RoomNumber = input.ReadUInt64();
            break;
          }
          case 32: {
            ChatId = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (senderInfo_ == null) {
              SenderInfo = new global::Chat.UserInfo();
            }
            input.ReadMessage(SenderInfo);
            break;
          }
          case 18: {
            if (chat_ == null) {
              Chat = new global::Chat.ChatIcon();
            }
            input.ReadMessage(Chat);
            break;
          }
          case 24: {
            RoomNumber = input.ReadUInt64();
            break;
          }
          case 32: {
            ChatId = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// The response of SSendChatText and SSendChatIcon
  /// </summary>
  public sealed partial class CSendChat : pb::IMessage<CSendChat>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CSendChat> _parser = new pb::MessageParser<CSendChat>(() => new CSendChat());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CSendChat> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Chat.ChatReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CSendChat() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CSendChat(CSendChat other) : this() {
      error_ = other.error_;
      roomNumber_ = other.roomNumber_;
      chatId_ = other.chatId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CSendChat Clone() {
      return new CSendChat(this);
    }

    /// <summary>Field number for the "error" field.</summary>
    public const int ErrorFieldNumber = 1;
    private global::Chat.SendChatError error_ = global::Chat.SendChatError.Invalid;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Chat.SendChatError Error {
      get { return error_; }
      set {
        error_ = value;
      }
    }

    /// <summary>Field number for the "room_number" field.</summary>
    public const int RoomNumberFieldNumber = 2;
    private ulong roomNumber_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong RoomNumber {
      get { return roomNumber_; }
      set {
        roomNumber_ = value;
      }
    }

    /// <summary>Field number for the "chat_id" field.</summary>
    public const int ChatIdFieldNumber = 3;
    private int chatId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ChatId {
      get { return chatId_; }
      set {
        chatId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CSendChat);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CSendChat other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Error != other.Error) return false;
      if (RoomNumber != other.RoomNumber) return false;
      if (ChatId != other.ChatId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Error != global::Chat.SendChatError.Invalid) hash ^= Error.GetHashCode();
      if (RoomNumber != 0UL) hash ^= RoomNumber.GetHashCode();
      if (ChatId != 0) hash ^= ChatId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Error != global::Chat.SendChatError.Invalid) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Error);
      }
      if (RoomNumber != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(RoomNumber);
      }
      if (ChatId != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(ChatId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Error != global::Chat.SendChatError.Invalid) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Error);
      }
      if (RoomNumber != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(RoomNumber);
      }
      if (ChatId != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(ChatId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Error != global::Chat.SendChatError.Invalid) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Error);
      }
      if (RoomNumber != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(RoomNumber);
      }
      if (ChatId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ChatId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CSendChat other) {
      if (other == null) {
        return;
      }
      if (other.Error != global::Chat.SendChatError.Invalid) {
        Error = other.Error;
      }
      if (other.RoomNumber != 0UL) {
        RoomNumber = other.RoomNumber;
      }
      if (other.ChatId != 0) {
        ChatId = other.ChatId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Error = (global::Chat.SendChatError) input.ReadEnum();
            break;
          }
          case 16: {
            RoomNumber = input.ReadUInt64();
            break;
          }
          case 24: {
            ChatId = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Error = (global::Chat.SendChatError) input.ReadEnum();
            break;
          }
          case 16: {
            RoomNumber = input.ReadUInt64();
            break;
          }
          case 24: {
            ChatId = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// The text chat packet for broadcasting
  /// </summary>
  public sealed partial class CChatText : pb::IMessage<CChatText>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CChatText> _parser = new pb::MessageParser<CChatText>(() => new CChatText());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CChatText> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Chat.ChatReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CChatText() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CChatText(CChatText other) : this() {
      senderInfo_ = other.senderInfo_ != null ? other.senderInfo_.Clone() : null;
      chat_ = other.chat_ != null ? other.chat_.Clone() : null;
      roomNumber_ = other.roomNumber_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CChatText Clone() {
      return new CChatText(this);
    }

    /// <summary>Field number for the "sender_info" field.</summary>
    public const int SenderInfoFieldNumber = 1;
    private global::Chat.UserInfo senderInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Chat.UserInfo SenderInfo {
      get { return senderInfo_; }
      set {
        senderInfo_ = value;
      }
    }

    /// <summary>Field number for the "chat" field.</summary>
    public const int ChatFieldNumber = 2;
    private global::Chat.ChatText chat_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Chat.ChatText Chat {
      get { return chat_; }
      set {
        chat_ = value;
      }
    }

    /// <summary>Field number for the "room_number" field.</summary>
    public const int RoomNumberFieldNumber = 3;
    private ulong roomNumber_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong RoomNumber {
      get { return roomNumber_; }
      set {
        roomNumber_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CChatText);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CChatText other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(SenderInfo, other.SenderInfo)) return false;
      if (!object.Equals(Chat, other.Chat)) return false;
      if (RoomNumber != other.RoomNumber) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (senderInfo_ != null) hash ^= SenderInfo.GetHashCode();
      if (chat_ != null) hash ^= Chat.GetHashCode();
      if (RoomNumber != 0UL) hash ^= RoomNumber.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (senderInfo_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(SenderInfo);
      }
      if (chat_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Chat);
      }
      if (RoomNumber != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(RoomNumber);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (senderInfo_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(SenderInfo);
      }
      if (chat_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Chat);
      }
      if (RoomNumber != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(RoomNumber);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (senderInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SenderInfo);
      }
      if (chat_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Chat);
      }
      if (RoomNumber != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(RoomNumber);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CChatText other) {
      if (other == null) {
        return;
      }
      if (other.senderInfo_ != null) {
        if (senderInfo_ == null) {
          SenderInfo = new global::Chat.UserInfo();
        }
        SenderInfo.MergeFrom(other.SenderInfo);
      }
      if (other.chat_ != null) {
        if (chat_ == null) {
          Chat = new global::Chat.ChatText();
        }
        Chat.MergeFrom(other.Chat);
      }
      if (other.RoomNumber != 0UL) {
        RoomNumber = other.RoomNumber;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (senderInfo_ == null) {
              SenderInfo = new global::Chat.UserInfo();
            }
            input.ReadMessage(SenderInfo);
            break;
          }
          case 18: {
            if (chat_ == null) {
              Chat = new global::Chat.ChatText();
            }
            input.ReadMessage(Chat);
            break;
          }
          case 24: {
            RoomNumber = input.ReadUInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (senderInfo_ == null) {
              SenderInfo = new global::Chat.UserInfo();
            }
            input.ReadMessage(SenderInfo);
            break;
          }
          case 18: {
            if (chat_ == null) {
              Chat = new global::Chat.ChatText();
            }
            input.ReadMessage(Chat);
            break;
          }
          case 24: {
            RoomNumber = input.ReadUInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// The icon chat packet for broadcasting
  /// </summary>
  public sealed partial class CChatIcon : pb::IMessage<CChatIcon>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CChatIcon> _parser = new pb::MessageParser<CChatIcon>(() => new CChatIcon());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CChatIcon> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Chat.ChatReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CChatIcon() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CChatIcon(CChatIcon other) : this() {
      senderInfo_ = other.senderInfo_ != null ? other.senderInfo_.Clone() : null;
      chat_ = other.chat_ != null ? other.chat_.Clone() : null;
      roomNumber_ = other.roomNumber_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CChatIcon Clone() {
      return new CChatIcon(this);
    }

    /// <summary>Field number for the "sender_info" field.</summary>
    public const int SenderInfoFieldNumber = 1;
    private global::Chat.UserInfo senderInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Chat.UserInfo SenderInfo {
      get { return senderInfo_; }
      set {
        senderInfo_ = value;
      }
    }

    /// <summary>Field number for the "chat" field.</summary>
    public const int ChatFieldNumber = 2;
    private global::Chat.ChatIcon chat_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Chat.ChatIcon Chat {
      get { return chat_; }
      set {
        chat_ = value;
      }
    }

    /// <summary>Field number for the "room_number" field.</summary>
    public const int RoomNumberFieldNumber = 3;
    private ulong roomNumber_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong RoomNumber {
      get { return roomNumber_; }
      set {
        roomNumber_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CChatIcon);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CChatIcon other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(SenderInfo, other.SenderInfo)) return false;
      if (!object.Equals(Chat, other.Chat)) return false;
      if (RoomNumber != other.RoomNumber) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (senderInfo_ != null) hash ^= SenderInfo.GetHashCode();
      if (chat_ != null) hash ^= Chat.GetHashCode();
      if (RoomNumber != 0UL) hash ^= RoomNumber.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (senderInfo_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(SenderInfo);
      }
      if (chat_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Chat);
      }
      if (RoomNumber != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(RoomNumber);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (senderInfo_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(SenderInfo);
      }
      if (chat_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Chat);
      }
      if (RoomNumber != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(RoomNumber);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (senderInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SenderInfo);
      }
      if (chat_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Chat);
      }
      if (RoomNumber != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(RoomNumber);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CChatIcon other) {
      if (other == null) {
        return;
      }
      if (other.senderInfo_ != null) {
        if (senderInfo_ == null) {
          SenderInfo = new global::Chat.UserInfo();
        }
        SenderInfo.MergeFrom(other.SenderInfo);
      }
      if (other.chat_ != null) {
        if (chat_ == null) {
          Chat = new global::Chat.ChatIcon();
        }
        Chat.MergeFrom(other.Chat);
      }
      if (other.RoomNumber != 0UL) {
        RoomNumber = other.RoomNumber;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (senderInfo_ == null) {
              SenderInfo = new global::Chat.UserInfo();
            }
            input.ReadMessage(SenderInfo);
            break;
          }
          case 18: {
            if (chat_ == null) {
              Chat = new global::Chat.ChatIcon();
            }
            input.ReadMessage(Chat);
            break;
          }
          case 24: {
            RoomNumber = input.ReadUInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (senderInfo_ == null) {
              SenderInfo = new global::Chat.UserInfo();
            }
            input.ReadMessage(SenderInfo);
            break;
          }
          case 18: {
            if (chat_ == null) {
              Chat = new global::Chat.ChatIcon();
            }
            input.ReadMessage(Chat);
            break;
          }
          case 24: {
            RoomNumber = input.ReadUInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ChatBase : pb::IMessage<ChatBase>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ChatBase> _parser = new pb::MessageParser<ChatBase>(() => new ChatBase());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ChatBase> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Chat.ChatReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChatBase() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChatBase(ChatBase other) : this() {
      chatDbId_ = other.chatDbId_;
      chatType_ = other.chatType_;
      timestamp_ = other.timestamp_ != null ? other.timestamp_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChatBase Clone() {
      return new ChatBase(this);
    }

    /// <summary>Field number for the "chat_db_id" field.</summary>
    public const int ChatDbIdFieldNumber = 1;
    private ulong chatDbId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong ChatDbId {
      get { return chatDbId_; }
      set {
        chatDbId_ = value;
      }
    }

    /// <summary>Field number for the "chat_type" field.</summary>
    public const int ChatTypeFieldNumber = 2;
    private global::Chat.ChatType chatType_ = global::Chat.ChatType.Invalid;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Chat.ChatType ChatType {
      get { return chatType_; }
      set {
        chatType_ = value;
      }
    }

    /// <summary>Field number for the "timestamp" field.</summary>
    public const int TimestampFieldNumber = 3;
    private global::Google.Protobuf.WellKnownTypes.Timestamp timestamp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp Timestamp {
      get { return timestamp_; }
      set {
        timestamp_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ChatBase);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ChatBase other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ChatDbId != other.ChatDbId) return false;
      if (ChatType != other.ChatType) return false;
      if (!object.Equals(Timestamp, other.Timestamp)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ChatDbId != 0UL) hash ^= ChatDbId.GetHashCode();
      if (ChatType != global::Chat.ChatType.Invalid) hash ^= ChatType.GetHashCode();
      if (timestamp_ != null) hash ^= Timestamp.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ChatDbId != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(ChatDbId);
      }
      if (ChatType != global::Chat.ChatType.Invalid) {
        output.WriteRawTag(16);
        output.WriteEnum((int) ChatType);
      }
      if (timestamp_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Timestamp);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ChatDbId != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(ChatDbId);
      }
      if (ChatType != global::Chat.ChatType.Invalid) {
        output.WriteRawTag(16);
        output.WriteEnum((int) ChatType);
      }
      if (timestamp_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Timestamp);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ChatDbId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(ChatDbId);
      }
      if (ChatType != global::Chat.ChatType.Invalid) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ChatType);
      }
      if (timestamp_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Timestamp);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ChatBase other) {
      if (other == null) {
        return;
      }
      if (other.ChatDbId != 0UL) {
        ChatDbId = other.ChatDbId;
      }
      if (other.ChatType != global::Chat.ChatType.Invalid) {
        ChatType = other.ChatType;
      }
      if (other.timestamp_ != null) {
        if (timestamp_ == null) {
          Timestamp = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        Timestamp.MergeFrom(other.Timestamp);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ChatDbId = input.ReadUInt64();
            break;
          }
          case 16: {
            ChatType = (global::Chat.ChatType) input.ReadEnum();
            break;
          }
          case 26: {
            if (timestamp_ == null) {
              Timestamp = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Timestamp);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ChatDbId = input.ReadUInt64();
            break;
          }
          case 16: {
            ChatType = (global::Chat.ChatType) input.ReadEnum();
            break;
          }
          case 26: {
            if (timestamp_ == null) {
              Timestamp = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(Timestamp);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ChatText : pb::IMessage<ChatText>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ChatText> _parser = new pb::MessageParser<ChatText>(() => new ChatText());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ChatText> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Chat.ChatReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChatText() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChatText(ChatText other) : this() {
      chatBase_ = other.chatBase_ != null ? other.chatBase_.Clone() : null;
      msg_ = other.msg_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChatText Clone() {
      return new ChatText(this);
    }

    /// <summary>Field number for the "chat_base" field.</summary>
    public const int ChatBaseFieldNumber = 1;
    private global::Chat.ChatBase chatBase_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Chat.ChatBase ChatBase {
      get { return chatBase_; }
      set {
        chatBase_ = value;
      }
    }

    /// <summary>Field number for the "msg" field.</summary>
    public const int MsgFieldNumber = 2;
    private string msg_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Msg {
      get { return msg_; }
      set {
        msg_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ChatText);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ChatText other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(ChatBase, other.ChatBase)) return false;
      if (Msg != other.Msg) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (chatBase_ != null) hash ^= ChatBase.GetHashCode();
      if (Msg.Length != 0) hash ^= Msg.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (chatBase_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(ChatBase);
      }
      if (Msg.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Msg);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (chatBase_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(ChatBase);
      }
      if (Msg.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Msg);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (chatBase_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ChatBase);
      }
      if (Msg.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Msg);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ChatText other) {
      if (other == null) {
        return;
      }
      if (other.chatBase_ != null) {
        if (chatBase_ == null) {
          ChatBase = new global::Chat.ChatBase();
        }
        ChatBase.MergeFrom(other.ChatBase);
      }
      if (other.Msg.Length != 0) {
        Msg = other.Msg;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (chatBase_ == null) {
              ChatBase = new global::Chat.ChatBase();
            }
            input.ReadMessage(ChatBase);
            break;
          }
          case 18: {
            Msg = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (chatBase_ == null) {
              ChatBase = new global::Chat.ChatBase();
            }
            input.ReadMessage(ChatBase);
            break;
          }
          case 18: {
            Msg = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ChatIcon : pb::IMessage<ChatIcon>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ChatIcon> _parser = new pb::MessageParser<ChatIcon>(() => new ChatIcon());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ChatIcon> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Chat.ChatReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChatIcon() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChatIcon(ChatIcon other) : this() {
      chatBase_ = other.chatBase_ != null ? other.chatBase_.Clone() : null;
      iconId_ = other.iconId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChatIcon Clone() {
      return new ChatIcon(this);
    }

    /// <summary>Field number for the "chat_base" field.</summary>
    public const int ChatBaseFieldNumber = 1;
    private global::Chat.ChatBase chatBase_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Chat.ChatBase ChatBase {
      get { return chatBase_; }
      set {
        chatBase_ = value;
      }
    }

    /// <summary>Field number for the "icon_id" field.</summary>
    public const int IconIdFieldNumber = 2;
    private uint iconId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint IconId {
      get { return iconId_; }
      set {
        iconId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ChatIcon);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ChatIcon other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(ChatBase, other.ChatBase)) return false;
      if (IconId != other.IconId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (chatBase_ != null) hash ^= ChatBase.GetHashCode();
      if (IconId != 0) hash ^= IconId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (chatBase_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(ChatBase);
      }
      if (IconId != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(IconId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (chatBase_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(ChatBase);
      }
      if (IconId != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(IconId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (chatBase_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ChatBase);
      }
      if (IconId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(IconId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ChatIcon other) {
      if (other == null) {
        return;
      }
      if (other.chatBase_ != null) {
        if (chatBase_ == null) {
          ChatBase = new global::Chat.ChatBase();
        }
        ChatBase.MergeFrom(other.ChatBase);
      }
      if (other.IconId != 0) {
        IconId = other.IconId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (chatBase_ == null) {
              ChatBase = new global::Chat.ChatBase();
            }
            input.ReadMessage(ChatBase);
            break;
          }
          case 16: {
            IconId = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (chatBase_ == null) {
              ChatBase = new global::Chat.ChatBase();
            }
            input.ReadMessage(ChatBase);
            break;
          }
          case 16: {
            IconId = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
